import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useApp } from '../context/AppContext';
import { formatDate, formatTime, getCurrentDate } from '../utils/helpers';
import { KEYS, loadData, saveData } from '../utils/storage';

const VERSION = '3.0.4';
const languages = [
  ['en', 'EN', 'English', 'English'], ['hi', 'HI', 'हिंदी', 'Hindi'], ['gu', 'GU', 'ગુજરાતી', 'Gujarati'],
  ['mr', 'MR', 'मराठी', 'Marathi'], ['kn', 'KN', 'ಕನ್ನಡ', 'Kannada'], ['te', 'TE', 'తెలుగు', 'Telugu'], ['ta', 'TA', 'தமிழ்', 'Tamil'],
];
const copy = {
  en: { dashboard: 'Dashboard', profile: 'My Profile', shifts: 'Upcoming Shifts', documents: 'My Documents', loans: 'Loan & Advance', arrears: 'Arrears', holidays: 'Holidays List', language: 'App Language', update: 'Check Update', logout: 'Logout', welcome: 'Welcome back', attendance: 'My Attendance', checkIn: 'Check in', checkOut: 'Check out', noRecords: 'No records found', apply: 'Apply', save: 'Save Changes', loading: 'Loading...', latest: 'You are using the latest version.', upload: 'Upload Document', uploaded: 'Uploaded', noData: "Oops! We couldn't find anything to show" },
  hi: { dashboard: 'डैशबोर्ड', profile: 'मेरी प्रोफ़ाइल', shifts: 'आगामी शिफ्ट', documents: 'मेरे दस्तावेज़', loans: 'ऋण और अग्रिम', arrears: 'बकाया', holidays: 'छुट्टियों की सूची', language: 'ऐप भाषा', update: 'अपडेट देखें', logout: 'लॉग आउट', welcome: 'आपका स्वागत है', attendance: 'मेरी उपस्थिति', checkIn: 'चेक इन', checkOut: 'चेक आउट', noRecords: 'कोई रिकॉर्ड नहीं मिला', apply: 'लागू करें', save: 'बदलाव सहेजें', loading: 'लोड हो रहा है...', latest: 'आप नवीनतम संस्करण का उपयोग कर रहे हैं।', upload: 'दस्तावेज़ अपलोड करें', uploaded: 'अपलोड हो गया', noData: 'दिखाने के लिए कुछ नहीं मिला' },
  gu: { dashboard: 'ડેશબોર્ડ', profile: 'મારી પ્રોફાઇલ', shifts: 'આગામી શિફ્ટ', documents: 'મારા દસ્તાવેજો', loans: 'લોન અને એડવાન્સ', arrears: 'બાકી રકમ', holidays: 'રજાઓની યાદી', language: 'એપ ભાષા', update: 'અપડેટ તપાસો', logout: 'લોગ આઉટ', welcome: 'સ્વાગત છે', attendance: 'મારી હાજરી', checkIn: 'ચેક ઇન', checkOut: 'ચેક આઉટ', noRecords: 'કોઈ રેકોર્ડ મળ્યો નથી', apply: 'લાગુ કરો', save: 'ફેરફાર સાચવો', loading: 'લોડ થઈ રહ્યું છે...', latest: 'તમે નવીનતમ સંસ્કરણનો ઉપયોગ કરી રહ્યા છો.', upload: 'દસ્તાવેજ અપલોડ કરો', uploaded: 'અપલોડ થયું', noData: 'બતાવવા માટે કંઈ મળ્યું નથી' },
  mr: { dashboard: 'डॅशबोर्ड', profile: 'माझे प्रोफाइल', shifts: 'आगामी शिफ्ट', documents: 'माझे दस्तऐवज', loans: 'कर्ज आणि आगाऊ', arrears: 'थकबाकी', holidays: 'सुट्टीची यादी', language: 'अॅप भाषा', update: 'अपडेट तपासा', logout: 'लॉग आउट', welcome: 'पुन्हा स्वागत आहे', attendance: 'माझी उपस्थिती', checkIn: 'चेक इन', checkOut: 'चेक आउट', noRecords: 'रेकॉर्ड सापडले नाही', apply: 'लागू करा', save: 'बदल जतन करा', loading: 'लोड होत आहे...', latest: 'तुम्ही नवीनतम आवृत्ती वापरत आहात.', upload: 'दस्तऐवज अपलोड करा', uploaded: 'अपलोड झाले', noData: 'दाखवण्यासाठी काहीही नाही' },
  kn: { dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್', shifts: 'ಮುಂಬರುವ ಶಿಫ್ಟ್‌ಗಳು', documents: 'ನನ್ನ ದಾಖಲೆಗಳು', loans: 'ಸಾಲ ಮತ್ತು ಮುಂಗಡ', arrears: 'ಬಾಕಿ', holidays: 'ರಜಾದಿನಗಳ ಪಟ್ಟಿ', language: 'ಆ್ಯಪ್ ಭಾಷೆ', update: 'ಅಪ್‌ಡೇಟ್ ಪರಿಶೀಲಿಸಿ', logout: 'ಲಾಗ್ ಔಟ್', welcome: 'ಮತ್ತೆ ಸ್ವಾಗತ', attendance: 'ನನ್ನ ಹಾಜರಾತಿ', checkIn: 'ಚೆಕ್ ಇನ್', checkOut: 'ಚೆಕ್ ಔಟ್', noRecords: 'ಯಾವುದೇ ದಾಖಲೆಗಳಿಲ್ಲ', apply: 'ಅನ್ವಯಿಸಿ', save: 'ಬದಲಾವಣೆ ಉಳಿಸಿ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', latest: 'ನೀವು ಇತ್ತೀಚಿನ ಆವೃತ್ತಿಯನ್ನು ಬಳಸುತ್ತಿದ್ದೀರಿ.', upload: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', uploaded: 'ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ', noData: 'ತೋರಿಸಲು ಏನೂ ಇಲ್ಲ' },
  te: { dashboard: 'డాష్‌బోర్డ్', profile: 'నా ప్రొఫైల్', shifts: 'రాబోయే షిఫ్ట్‌లు', documents: 'నా పత్రాలు', loans: 'లోన్ మరియు అడ్వాన్స్', arrears: 'బకాయిలు', holidays: 'సెలవుల జాబితా', language: 'యాప్ భాష', update: 'అప్‌డేట్ తనిఖీ', logout: 'లాగ్ అవుట్', welcome: 'మళ్లీ స్వాగతం', attendance: 'నా హాజరు', checkIn: 'చెక్ ఇన్', checkOut: 'చెక్ అవుట్', noRecords: 'రికార్డులు లేవు', apply: 'వర్తింపజేయి', save: 'మార్పులు సేవ్ చేయి', loading: 'లోడ్ అవుతోంది...', latest: 'మీరు తాజా వెర్షన్‌ను ఉపయోగిస్తున్నారు.', upload: 'పత్రాన్ని అప్‌లోడ్ చేయి', uploaded: 'అప్‌లోడ్ అయింది', noData: 'చూపించడానికి ఏమీ లేదు' },
  ta: { dashboard: 'டாஷ்போர்டு', profile: 'என் சுயவிவரம்', shifts: 'வரவிருக்கும் பணிகள்', documents: 'என் ஆவணங்கள்', loans: 'கடன் மற்றும் முன்பணம்', arrears: 'நிலுவைகள்', holidays: 'விடுமுறை பட்டியல்', language: 'ஆப் மொழி', update: 'புதுப்பிப்பைச் சரிபார்', logout: 'வெளியேறு', welcome: 'மீண்டும் வரவேற்கிறோம்', attendance: 'என் வருகை', checkIn: 'செக் இன்', checkOut: 'செக் அவுட்', noRecords: 'பதிவுகள் இல்லை', apply: 'பயன்படுத்து', save: 'மாற்றங்களைச் சேமி', loading: 'ஏற்றப்படுகிறது...', latest: 'நீங்கள் சமீபத்திய பதிப்பைப் பயன்படுத்துகிறீர்கள்.', upload: 'ஆவணத்தைப் பதிவேற்று', uploaded: 'பதிவேற்றப்பட்டது', noData: 'காண்பிக்க எதுவும் இல்லை' },
};
const documentItems = [
  ['aadhaar-front', 'Aadhaar Card', 'Front Side', 2], ['aadhaar-back', 'Aadhaar Card', 'Back Side', 2],
  ['pan', 'PAN Card', 'Add PAN Card', 2], ['dl-front', 'Driving Licence', 'Front Side', 2], ['dl-back', 'Driving Licence', 'Back Side', 2],
];
const holidays = [
  { name: 'Republic Day', date: '2026-01-26', type: 'National' }, { name: 'Holi', date: '2026-03-04', type: 'Festival' },
  { name: 'Independence Day', date: '2026-08-15', type: 'National' }, { name: 'Diwali', date: '2026-11-08', type: 'Festival' },
  { name: 'Christmas', date: '2026-12-25', type: 'Festival' },
];

function Icon({ name }) {
  const paths = { home: 'M3 11l9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z', user: 'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm-7 9a7 7 0 0 1 14 0', doc: 'M6 2h9l3 3v17H6zM9 13h6M9 17h6M9 9h3', cal: 'M5 4h14a1 1 0 0 1 1 1v15H4V5a1 1 0 0 1 1-1zm3-2v4m8-4v4M4 9h16', wallet: 'M4 6h16v13H4zM4 9h16m-5 5h3', globe: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18zm0-18c2 2.2 3 5.2 3 9s-1 6.8-3 9c-2-2.2-3-5.2-3-9s1-6.8 3-9z', upload: 'M12 16V4m0 0L7 9m5-5 5 5M5 20h14', back: 'M15 18l-6-6 6-6', check: 'M5 12l4 4L19 6', menu: 'M4 6h16M4 12h16M4 18h16', info: 'M12 8v4m0 4h.01M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18' };
  return <svg className="portal-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.info} /></svg>;
}

function EmptyState({ text }) { return <div className="portal-empty"><div className="portal-empty-icon"><Icon name="doc" /></div><strong>{text}</strong></div>; }

export default function EmployeePortalPage() {
  const { user, logout } = useAuth();
  const { employees, attendance, checkIn, checkOut, addToast } = useApp();
  const navigate = useNavigate();
  const employee = employees.find((item) => item.id === user?.employeeId);
  const [screen, setScreen] = useState('dashboard');
  const [drawer, setDrawer] = useState(false);
  const [language, setLanguage] = useState(() => loadData(KEYS.EMPLOYEE_LANGUAGE, 'en'));
  const [draftLanguage, setDraftLanguage] = useState(language);
  const [year, setYear] = useState(new Date().getFullYear());
  const [loanTab, setLoanTab] = useState('active');
  const [documents, setDocuments] = useState(() => loadData(KEYS.EMPLOYEE_DOCUMENTS, {}));
  const [uploading, setUploading] = useState(null);
  const [uploadError, setUploadError] = useState('');
  const [updateChecked, setUpdateChecked] = useState(false);
  const fileRef = useRef(null);
  const uploadTarget = useRef(null);
  const t = copy[language] || copy.en;
  const employeeId = user?.employeeId;
  const ownAttendance = useMemo(() => attendance.filter((item) => item.employeeId === employeeId).sort((a, b) => `${b.date} ${b.checkIn || ''}`.localeCompare(`${a.date} ${a.checkIn || ''}`)), [attendance, employeeId]);
  const todayRecord = ownAttendance.find((item) => item.date === getCurrentDate());
  const storedLoans = loadData(KEYS.EMPLOYEE_LOANS, {});
  const loans = storedLoans[user?.employeeId] || [];
  const storedArrears = loadData(KEYS.EMPLOYEE_ARREARS, {});
  const arrears = storedArrears[user?.employeeId] || [];
  const storedShifts = loadData(KEYS.EMPLOYEE_SHIFTS, {});
  const shifts = storedShifts[user?.employeeId] || Array.from({ length: 5 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() + index + 1); return { date: date.toISOString().slice(0, 10), name: employee?.shift || 'Default Shift', start: '09:30', end: '18:00', location: 'Main Office', status: index === 0 ? 'Confirmed' : 'Upcoming' }; });
  const currentYearHolidays = holidays.filter((item) => new Date(item.date).getFullYear() === Number(year));
  const totals = loans.reduce((result, item) => ({ amount: result.amount + Number(item.amount || 0), paid: result.paid + Number(item.paid || 0), outstanding: result.outstanding + Math.max(0, Number(item.amount || 0) - Number(item.paid || 0)) }), { amount: 0, paid: 0, outstanding: 0 });

  useEffect(() => { saveData(KEYS.EMPLOYEE_DOCUMENTS, documents); }, [documents]);

  const closeDrawer = () => setDrawer(false);
  const go = (next) => { setScreen(next); closeDrawer(); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const handleLogout = () => { logout(); navigate('/employee-login', { replace: true }); };
  const money = (value) => `₹ ${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  const handleAttendance = async (action) => { const result = await (action === 'in' ? checkIn(user.employeeId) : checkOut(user.employeeId)); addToast(result.success ? `${action === 'in' ? 'Check-in' : 'Check-out'} recorded` : result.error, result.success ? 'success' : 'error'); };
  const openUpload = (item) => { uploadTarget.current = item; fileRef.current?.click(); };
  const handleUpload = (event) => {
    const file = event.target.files?.[0]; event.target.value = ''; if (!file || !uploadTarget.current) return;
    const item = uploadTarget.current; const extension = file.name.split('.').pop().toLowerCase(); const valid = ['jpg', 'jpeg', 'png', 'pdf'];
    if (!valid.includes(extension)) { setUploadError('Only JPG, PNG, and PDF files are supported.'); return; }
    const max = extension === 'pdf' ? 1024 * 1024 : 2 * 1024 * 1024;
    if (file.size > max) { setUploadError(extension === 'pdf' ? 'PDF files must be 1 MB or smaller.' : 'JPG and PNG files must be 2 MB or smaller.'); return; }
    setUploadError(''); setUploading(item.id); const reader = new FileReader(); reader.onload = () => { setTimeout(() => { setDocuments((previous) => ({ ...previous, [user.employeeId]: { ...(previous[user.employeeId] || {}), [item.id]: { name: file.name, type: file.type, size: file.size, data: reader.result, uploadedAt: new Date().toISOString() } } })); setUploading(null); addToast('Document uploaded successfully'); }, 500); }; reader.readAsDataURL(file);
  };

  if (!employee) return <div className="employee-portal"><div className="portal-card"><h2>Employee account unavailable</h2><button className="btn btn-primary" onClick={handleLogout}>Log out</button></div></div>;
  const myDocuments = documents[user.employeeId] || {};
  const menu = [['dashboard', t.dashboard, 'home'], ['profile', t.profile, 'user'], ['shifts', t.shifts, 'cal'], ['documents', t.documents, 'doc'], ['loans', t.loans, 'wallet'], ['arrears', t.arrears, 'wallet'], ['holidays', t.holidays, 'cal'], ['language', t.language, 'globe'], ['update', t.update, 'info']];

  return <div className="employee-portal">
    <header className="portal-topbar employee-portal-header"><button className="portal-menu-button" onClick={() => setDrawer(true)} aria-label="Open menu"><Icon name="menu" /></button><div className="portal-brand"><strong>Attendo</strong><span>Employee App</span></div><div className="portal-header-actions"><button className="portal-avatar-button" onClick={() => go('profile')} aria-label="Open profile">{employee.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()}</button><button className="portal-header-logout" onClick={handleLogout}>Log out</button></div></header>
    {drawer && <div className="portal-scrim" onClick={closeDrawer} />}
    <aside className={`portal-drawer ${drawer ? 'is-open' : ''}`}><div className="portal-drawer-head"><div className="portal-avatar-large">{employee.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()}</div><div><strong>{employee.name}</strong><small>{employee.id.toUpperCase()}</small></div><button className="portal-close" onClick={closeDrawer}>×</button></div><nav>{menu.map(([id, label, icon]) => <button key={id} className={screen === id ? 'active' : ''} onClick={() => go(id)}><Icon name={icon} /><span>{label}</span><Icon name="back" /></button>)}<button className="portal-menu-disabled"><Icon name="info" /><span>Mediclaim</span><em>Coming Soon</em></button></nav><div className="portal-drawer-foot"><button className="portal-logout" onClick={handleLogout}><Icon name="back" />{t.logout}</button><small>v{VERSION}</small></div></aside>
    <main className="employee-portal-content portal-main">
      {screen !== 'dashboard' && <button className="portal-back" onClick={() => go('dashboard')}><Icon name="back" /> {t.dashboard}</button>}
      {screen === 'dashboard' && <DashboardView employee={employee} user={user} t={t} todayRecord={todayRecord} ownAttendance={ownAttendance} onAttendance={handleAttendance} />}
      {screen === 'profile' && <ProfileView employee={employee} t={t} />}
      {screen === 'shifts' && <ShiftsView shifts={shifts} t={t} />}
      {screen === 'documents' && <DocumentsView items={documentItems} documents={myDocuments} uploading={uploading} error={uploadError} onUpload={openUpload} t={t} />}
      {screen === 'loans' && <LoansView loans={loans} totals={totals} tab={loanTab} setTab={setLoanTab} money={money} t={t} />}
      {screen === 'arrears' && <ArrearsView arrears={arrears} money={money} t={t} />}
      {screen === 'holidays' && <HolidaysView holidays={currentYearHolidays} year={year} setYear={setYear} t={t} />}
      {screen === 'language' && <LanguageView draft={draftLanguage} setDraft={setDraftLanguage} apply={() => { setLanguage(draftLanguage); saveData(KEYS.EMPLOYEE_LANGUAGE, draftLanguage); addToast('Language updated'); }} t={t} />}
      {screen === 'update' && <UpdateView checked={updateChecked} check={() => setUpdateChecked(true)} t={t} />}
    </main><input ref={fileRef} type="file" accept=".jpg,.jpeg,.png,.pdf,image/jpeg,image/png,application/pdf" onChange={handleUpload} hidden />
  </div>;
}

function DashboardView({ employee, t, todayRecord, ownAttendance, onAttendance }) { return <><section className="portal-hero"><div><span>{t.welcome}</span><h1>{employee.name}</h1><p>{employee.designation} · {employee.department}</p></div><div className="portal-id"><span>Employee ID</span><strong>{employee.id.toUpperCase()}</strong></div></section><section className="portal-grid"><div className="portal-card"><span className="portal-label">Today</span><strong className="portal-value">{todayRecord?.status || 'Not checked in'}</strong><span>{todayRecord?.checkIn ? `In ${formatTime(todayRecord.checkIn)}` : 'Your attendance status'}</span></div><div className="portal-card"><span className="portal-label">Shift</span><strong className="portal-value">{employee.shift}</strong><span>{employee.status} employee</span></div><div className="portal-card portal-actions"><span className="portal-label">Attendance action</span>{!todayRecord ? <button className="btn btn-primary" onClick={() => onAttendance('in')}>{t.checkIn}</button> : !todayRecord.checkOut ? <button className="btn btn-primary" onClick={() => onAttendance('out')}>{t.checkOut}</button> : <span>Completed for today</span>}</div></section><section className="portal-card portal-history"><div className="section-heading"><h2>{t.attendance}</h2><span>{ownAttendance.length} records</span></div><AttendanceTable records={ownAttendance} empty={t.noRecords} /></section></>; }
function AttendanceTable({ records, empty }) { return <div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Shift</th><th>Check In</th><th>Check Out</th><th>Status</th><th>Hours</th></tr></thead><tbody>{records.length === 0 ? <tr><td colSpan="6" className="empty-cell">{empty}</td></tr> : records.map((record) => <tr key={record.id}><td>{formatDate(record.date)}</td><td>{record.shift}</td><td>{formatTime(record.checkIn)}</td><td>{formatTime(record.checkOut)}</td><td><span className="portal-status">{record.status}</span></td><td>{record.totalHours || 0}h</td></tr>)}</tbody></table></div>; }
function ProfileView({ employee }) { return <section className="portal-section"><div className="portal-profile-card"><div className="portal-avatar-xl">{employee.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()}</div><h1>{employee.name}</h1><p>{employee.designation}</p><strong>{employee.id.toUpperCase()}</strong></div><div className="portal-detail-grid">{[['Department', employee.department], ['Joining date', formatDate(employee.joiningDate)], ['Mobile number', employee.phone], ['Email', employee.email], ['Work location', employee.location || 'Main Office'], ['Employment status', employee.status]].map(([label, value]) => <div className="portal-detail" key={label}><span>{label}</span><strong>{value || '-'}</strong></div>)}</div></section>; }
function ShiftsView({ shifts, t }) { return <section className="portal-section"><div className="portal-section-title"><div><span className="eyebrow">Schedule</span><h1>{t.shifts}</h1></div></div>{shifts.length ? <div className="portal-list">{shifts.map((shift) => <div className="shift-card" key={`${shift.date}-${shift.start}`}><div className="date-tile"><strong>{new Date(shift.date).getDate()}</strong><span>{new Date(shift.date).toLocaleDateString('en', { month: 'short' })}</span></div><div className="shift-info"><strong>{shift.name}</strong><span>{shift.start} - {shift.end} · {shift.location}</span></div><span className={`status-chip ${shift.status.toLowerCase()}`}>{shift.status}</span></div>)}</div> : <EmptyState text="No upcoming shifts" />}</section>; }
function DocumentsView({ items, documents, uploading, error, onUpload, t }) { return <section className="portal-section"><div className="portal-section-title"><div><span className="eyebrow">Secure storage</span><h1>{t.documents}</h1></div></div>{error && <div className="portal-alert error"><Icon name="info" />{error}</div>}<div className="document-list">{items.map((item) => { const [id, category, label] = item; const uploaded = documents[id]; return <div className="document-row" key={id}><div className="document-icon"><Icon name={uploaded ? 'check' : 'upload'} /></div><div className="document-info"><span>{category}</span><strong>{label}</strong>{uploaded && <small>{t.uploaded} · {uploaded.name}</small>}</div>{uploaded ? <a className="document-action uploaded" href={uploaded.data} download={uploaded.name} target="_blank" rel="noreferrer">View</a> : <button className="document-action" onClick={() => onUpload(item)} disabled={uploading === id}>{uploading === id ? t.loading : t.upload}</button>}<Icon name="back" /></div>; })}</div><div className="portal-alert"><Icon name="info" /><span>File formats: JPG, PNG (max 2 MB) or PDF (max 1 MB)<br /><small>Once uploaded, this file cannot be replaced or deleted. Please review it before uploading.</small></span></div></section>; }
function LoansView({ loans, totals, tab, setTab, money, t }) { const visible = loans.filter((loan) => tab === 'active' ? loan.status !== 'Completed' : loan.status === 'Completed'); return <section className="portal-section"><div className="portal-section-title"><div><span className="eyebrow">Finance</span><h1>{t.loans}</h1></div></div><div className="finance-summary"><div><span>Total Amount</span><strong>{money(totals.amount)}</strong></div><div><span>Total Paid</span><strong className="green">{money(totals.paid)}</strong></div><div><span>Outstanding</span><strong className="red">{money(totals.outstanding)}</strong></div></div><div className="portal-tabs"><button className={tab === 'active' ? 'active' : ''} onClick={() => setTab('active')}>Active</button><button className={tab === 'completed' ? 'active' : ''} onClick={() => setTab('completed')}>Completed</button></div>{visible.length ? <div className="portal-list">{visible.map((loan) => <div className="finance-row" key={loan.id}><div><strong>{loan.title}</strong><span>{formatDate(loan.date)} · EMI {money(loan.emi)}</span></div><strong>{money(loan.amount - loan.paid)}</strong></div>)}</div> : <EmptyState text={t.noData} />}</section>; }
function ArrearsView({ arrears, money, t }) { return <section className="portal-section"><div className="portal-section-title"><div><span className="eyebrow">Payroll</span><h1>{t.arrears}</h1></div></div><div className="arrears-summary"><div><span>Total arrears</span><strong>{money(arrears.reduce((sum, item) => sum + Number(item.amount || 0), 0))}</strong></div><div><span>Pending arrears</span><strong className="red">{money(arrears.filter((item) => item.status !== 'Paid').reduce((sum, item) => sum + Number(item.amount || 0), 0))}</strong></div><div><span>Paid arrears</span><strong className="green">{money(arrears.filter((item) => item.status === 'Paid').reduce((sum, item) => sum + Number(item.amount || 0), 0))}</strong></div></div>{arrears.length ? <div className="portal-list">{arrears.map((item) => <div className="finance-row" key={item.id}><div><strong>{item.description}</strong><span>{formatDate(item.date)} · {item.details || 'Settlement pending'}</span></div><div><strong>{money(item.amount)}</strong><span className={`status-chip ${item.status === 'Paid' ? 'confirmed' : 'pending'}`}>{item.status}</span></div></div>)}</div> : <EmptyState text="No arrears found" />}</section>; }
function HolidaysView({ holidays: items, year, setYear, t }) { return <section className="portal-section"><div className="portal-section-title"><div><span className="eyebrow">Company calendar</span><h1>{t.holidays}</h1></div><select value={year} onChange={(event) => setYear(event.target.value)}><option>2026</option><option>2027</option><option>2028</option></select></div>{items.length ? <div className="portal-list">{items.map((item) => <div className={`holiday-row ${item.date >= getCurrentDate() ? 'upcoming' : ''}`} key={item.date}><div className="date-tile"><strong>{new Date(item.date).getDate()}</strong><span>{new Date(item.date).toLocaleDateString('en', { month: 'short' })}</span></div><div><strong>{item.name}</strong><span>{new Date(item.date).toLocaleDateString('en', { weekday: 'long' })} · {item.type}</span></div></div>)}</div> : <EmptyState text="No holidays available" />}</section>; }
function LanguageView({ draft, setDraft, apply, t }) { return <section className="portal-section"><div className="portal-section-title"><div><span className="eyebrow">Personalization</span><h1>{t.language}</h1><p>Select your preferable language</p></div></div><div className="language-list">{languages.map(([id, code, native, english]) => <button className={`language-card ${draft === id ? 'selected' : ''}`} key={id} onClick={() => setDraft(id)}><span className="language-code">{code}</span><span><strong>{native}</strong><small>{english}</small></span><span className="language-check">{draft === id && <Icon name="check" />}</span></button>)}</div><button className="btn btn-primary btn-block portal-apply" onClick={apply}>{t.apply}</button></section>; }
function UpdateView({ checked, check, t }) { return <section className="portal-section"><div className="portal-section-title"><div><span className="eyebrow">System</span><h1>{t.update}</h1></div></div><div className="update-card"><div className="update-icon"><Icon name="check" /></div><span>Current Version</span><strong>v{VERSION}</strong><p>{checked ? t.latest : 'Check for the latest employee app version.'}</p>{!checked && <button className="btn btn-primary" onClick={check}>Check for updates</button>}</div></section>; }
